---
- name: Install Python dependencies for AWS
  pip:
    name:
      - boto3
      - botocore
    state: present
  become: yes

- name: Create application directory structure
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'

- name: Get AWS credentials from Secrets Manager
  aws_secret:
    name: "my-app-deployment-creds"
    region: "us-east-2"
  register: aws_creds
  
- name: Download application from S3
  aws_s3:
    bucket: "{{ s3_bucket }}"
    object: "{{ s3_path }}"
    dest: "/tmp/flask_app.tar.gz"
    mode: get
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_creds.secret['access_key'] }}"
    aws_secret_key: "{{ aws_creds.secret['secret_key'] }}"

- name: Extract application
  unarchive:
    src: "/tmp/flask_app.tar.gz"
    dest: "{{ app_dir }}"
    remote_src: yes
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Create virtual environment
  pip:
    virtualenv: "{{ venv_path }}"
    requirements: "{{ app_dir }}/requirements.txt"
    virtualenv_command: python3 -m venv

- name: Install Gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{ venv_path }}"

- name: Configure systemd service
  template:
    src: flask-app.service.j2
    dest: /etc/systemd/system/flask-app.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart flask-app