---
- name: Deploy Flask App
  hosts: app_servers
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false  # Disable if not needed to speed up deployment

  vars:
    app_dir: /opt/flaskapp
    app_user: deploy
    s3_bucket: "team12-flask-artifact"
    s3_path: "artifacts/{{ build_number }}/{{ artifact_name }}"
    venv_path: "{{ app_dir }}/venv"

  tasks:
    - name: Validate build number
      fail:
        msg: "Build number is required"
      when: build_number is not defined

    - name: Install system dependencies
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - sqlite
      tags: packages

    - name: Include deployment tasks
  include_tasks: ansible/main.yaml



  handlers:
    - name: Restart flask-app
      systemd:
        name: flask-app
        state: restarted