---
- name: Deploy Flask App
  hosts: app_servers
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true  # Should be enabled for proper functioning

  vars:
    app_dir: /opt/flaskapp
    app_user: deploy
    s3_bucket: "team12-flask-artifact"
    s3_path: "artifacts/{{ build_number }}/flask_app.tar.gz"  # Fixed variable name
    venv_path: "{{ app_dir }}/venv"

  roles:
    - role: flask  # This is the proper way to include roles

  handlers:
    - name: Restart flask-app
      systemd:
        name: flask-app
        state: restarted