---
- name: Deploy Flask App
  hosts: app_servers
  become: true

  tasks:
    - name: Ensure necessary packages are installed
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - sqlite

    - name: Install Flask and boto3
      pip:
        name: 
          - flask
          - boto3

    - name: Create app directory if it doesn't exist
      file:
        path: /opt/flaskapp
        state: directory
        mode: '0755'

    - name: Download artifact from S3
      amazon.aws.aws_s3:
        bucket: "team12-flask-artifact"  # Corrected bucket name
        object: "artifacts/flask_app.tar.gz"
        dest: "/tmp/flask_app.tar.gz"
        mode: get
        overwrite: yes
      delegate_to: localhost
      become: false

    - name: Copy artifact to target server
      copy:
        src: "/tmp/flask_app.tar.gz"
        dest: "/tmp/flask_app.tar.gz"
        mode: '0644'
      become: true

    - name: Extract the app
      unarchive:
        src: /tmp/flask_app.tar.gz
        dest: /opt/flaskapp
        remote_src: yes

    - name: Initialize database
      shell: |
        cd /opt/flaskapp
        sqlite3 app/data.db < init_db.sql
      args:
        creates: /opt/flaskapp/app/data.db

    - name: Create Flask systemd service
      copy:
        dest: /etc/systemd/system/flask-app.service
        content: |
          [Unit]
          Description=Flask Web Application
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/opt/flaskapp
          ExecStart=/usr/bin/python3 /opt/flaskapp/app/app.py
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Flask service
      systemd:
        name: flask-app
        enabled: yes
        state: restarted
        daemon_reload: yes